### ISSUE TITLE
convert-2d.py: TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by alexcg1** [bmsleight/lasercut#29]
Loving the module! However, when trying to run `python convert-2d.py examples.scad` I'm getting the following error:

```
Traceback (most recent call last):
  File "/mnt/data/personal/art/be-excellent-sign/lightbox/imports/lasercut/convert-2d.py", line 257, in <module>
    output_abs_path = os.path.normcase(output_abs_path)
  File "/usr/lib/python3.10/posixpath.py", line 54, in normcase
    return os.fspath(s)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

## Reproduce error

1. `git clone` repo
2. `cd lasercut`
3. `python convert-2d.py examples.scad`

## System info

- OS: Manjaro Linux
- OpenSCAD version: 2021.01
- Python version: 3.10.2
- Location of `openscad` executable: `/usr/bin/openscad` (including because I think it might be looking for this and failing)

**Comment by alexcg1** [comment]
If i try to run `python ./convert-2d.py --keep examples.scad examples_flattened.dxf` as outlined in README, I get this error:

```
Processing "examples.scad"
Traceback (most recent call last):
  File "/mnt/data/personal/art/be-excellent-sign/lightbox/imports/lasercut/./convert-2d.py", line 268, in <module>
    process_scad_file(source_abs_path, processed_scad_path,
  File "/mnt/data/personal/art/be-excellent-sign/lightbox/imports/lasercut/./convert-2d.py", line 111, in process_scad_file
    cmd_output = subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '"openscad" "/mnt/data/personal/art/be-excellent-sign/lightbox/imports/lasercut/examples.scad" -D generate=1 -o "/mnt/data/personal/art/be-excellent-sign/lightbox/imports/lasercut/temp_examples_flattened.csg"'
```

**Comment by dcm684** [comment]
Looking through the script I see that the first issue is called with some variables not getting set.

I was able to replicate the second issue. Python in Linux requires the "subprocess.run()" calls to have parameter "shell=True". Windows (which is what I developed it on) doesn't require it.

I'll work on these issues in the next day or two and make a pull request.
